### ISSUE TITLE
is this project finish ? 

### ISSUE THREAD

**Issue by ogta** [ccali14/Touch#1]
i try registration but i take error.

Error:

<code>
An exception occurred while executing 'INSERT INTO fos_user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["oguzhan", "oguzhan", "oguzhantasc@gmail.com", "oguzhantasc@gmail.com", 1, "gmtlydkij6gckwkggk00cgoswgs0osc", "bhm55APgIomOiNvDLJt9LhFVJIkq7e8FNA1llWW\/U7f2+mFbIfYDWO3iFJTQ6uLF00YblBB3Y\/0bUHzUG49x5w==", null, 0, 0, null, null, null, "a:1:{i:0;s:11:\"ROLE_LEADER\";}", 0, null]:

</code>

**Comment by cagataycali** [comment]
Hi dear,
That's already published.But the error about u'r document's doesn't exits.U have to add , app/config/parameters.yml . and u'r config.I'm adding sql query's.Therefore u have to update your mysql db.

Merhabalar,
Bu proje tamamlanmıştır.Fakat sizin elinizdeki dosyaların içerisinde parameters.yml dosyası eksiktir.Kendi parameters.yml dosyanızı açıp içerisine kendi ayarlarınızı yazmanız ve veritabanınızı güncellemeniz gerekmektedir.

**Comment by ogta** [comment]
hi again, this error on your web site - http://www.gorev.li -

**Comment by cagataycali** [comment]
Let's check it out together, username : testt pass: 12345 and we can test together on this link. 
http://www.gorev.li/dashboard/#&togetherjs=7r8u6E04Qc

**Comment by cagataycali** [comment]
Log-in after click this link http://www.gorev.li/dashboard/#&togetherjs=7r8u6E04Qc

**Comment by ogta** [comment]
nice work :+1: 

lastly, u fix this area then everything is nice. http://hizliresim.com/mP3nyP
